#Workflow CI/CD
#Descripcion: Construye imagen docker y la publica como artefacto a traves de GHCR.IO en el repositorio.
name: FastApi ml model CI/CD
run-name: Creando artefacto (Imagen Docker) en GHCR 
on: [push]

env: 
    REGISTRY: ghcr.io
    IMAGE_NAME: themidnightguy/api_taller

jobs:
    #JOB-N1 - Setup inicial
    setup-runner:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
            attestations: write
            id-token: write

        steps:
        #checkout
        - name: Chequeo de código
          uses: actions/checkout@v4
        #Poetry cache on runner
        - name: Cache Poetry
          uses: actions/cache@v4
          with:
            path: ~/.cache/pypoetry
            key: ${{runner.os}}-poetry-${{hashFiles('**/poetry.lock')}}
            restore-keys: |
                ${{runner.os}}-poetry
        #Python
        - name: Python SetUp
          uses: actions/setup-python@v4
          with:
            python-version: "3.12.0"

        #Poetry
        - name: Poetry setup
          run: pip install poetry
        #Dependencias
        - name: Instalar dependencias
          run: poetry install --no-interaction --no-ansi

    #JOB-N2 - Build y push imagen a GHCR
    Build-Push-GHCR:
        needs: setup-runner
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
        #checkout
        - name: Chequeo de código
          uses: actions/checkout@v4
        #login ghcr (GitHub Container Registry)
        - name: login GHCR
          uses: docker/login-action@v3
          with:
            registry: ${{env.REGISTRY}}
            username: ${{github.actor}}
            password: ${{secrets.GITHUB_TOKEN}}

        #build-push-actions
        - name: Build & Push Docker image
          uses: docker/build-push-action@v6
          with: 
            push: true
            tags: ${{env.REGISTRY}}/${{env.IMAGE_NAME}}/api_taller_app:latest
            secrets: |
                GIT_AUTH_TOKEN=${{secrets.GITHUB_TOKEN}}